
language: java

jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk7

script:
  - javac -cp .:./lib/junit-4.12.jar Calculator.java CalculatorTest.java

after_success:
  - java -cp .:./lib/junit-4.12.jar org.junit.runner.JUnitCore CalculatorTest
